// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Alternativa;

{ITE} {DFMFileType} {vcl\DBLOGDLG.dfm}
{ITE} {DFMFileType} {vcl\DBPWDLG.dfm}
{ITE} {DFMFileType} {FormMain.dfm}
{ITE} {DFMFileType} {MailFotos.dfm}
{ITE} {DFMFileType} {Recurso.dfm}
{ITE} {DFMFileType} {TrabajoRealizado.dfm}
{ITE} {DFMFileType} {E\LIB\DELPHI\SG_Valor.dfm}
{ITE} {RCFileType} {Alternativa_DRC.rc}

{$R 'vcl\DBLOGDLG.dfm' LoginDialog:TForm(Form)}
{$R 'vcl\DBPWDLG.dfm' PasswordDialog:TForm(Form)}
{$R 'FormMain.dfm' FormAlternativa:TForm}
{$R 'MailFotos.dfm' FormMailFotos:TForm}
{$R 'Recurso.dfm' FormRecurso:TForm}
{$R 'TrabajoRealizado.dfm' FormTrabajoRealizado:TForm}
{$R 'E\LIB\DELPHI\SG_Valor.dfm' FormValor:TForm}
{$R 'Alternativa_DRC.res' 'Alternativa_DRC.rc'}

{$E PTB}

begin
end.